### ISSUE TITLE
试着运行了下并不是单行

### ISSUE THREAD

**Issue by noecs** [wxnacy/study#1]

**Comment by wxnacy** [comment]
> _No description provided._

请问运行的那个程序

**Comment by noecs** [comment]
https://github.com/wxnacy/study/blob/master/goland/src/progress/single.go

**Comment by wxnacy** [comment]
> https://github.com/wxnacy/study/blob/master/goland/src/progress/single.go

![progress](https://user-images.githubusercontent.com/7698847/60707128-94d02080-9f3d-11e9-94a0-48d7d02ef28f.gif)

**Comment by wxnacy** [comment]
以上是我在我这运行的效果

**Comment by noecs** [comment]
我确实运行了该代码，是单行
![code](https://upload-images.jianshu.io/upload_images/18113839-bf3d8753e9e881ca.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
